[package]
name = "memory-region"
version = "1.0.0"
description = "An abstraction over the Region type that supports reusing deallocated memory."
repository = "https://github.com/NatLabs/memory-region"
keywords = [ "region", "memory", "bytes", "deallocate", "collections" ]

[dependencies]
base = "0.11.1"
itertools = "0.2.1"
stableheapbtreemap = "1.5.0"
map = "9.0.1"
augmented-btrees = "0.4.0"

[dev-dependencies]
test = "1.2.0"
fuzz = "0.2.0"
bench = "1.0.0"
memory-region-v0_1_1 = "https://github.com/NatLabs/memory-region#main@682d5a477446c3955ad3fad1800cab1f85202ec5"

[toolchain]
wasmtime = "14.0.4"
moc = "0.10.4"
